openapi: 3.1.0
info:
  title: Combined Make87 Schemas
  version: 1.0.0
components:
  schemas:
    "make87_messages.detection.box.Box2DAxisAligned":
    "make87_messages.audio.FrameAac":
    "make87_messages.video.FrameMpegTsAV1":
    "make87_messages.primitive.SInt64":
    "make87_messages.image.uncompressed.ImageGray":
    "make87_messages.video.FrameMpegTsH264":
    "make87_messages.image.uncompressed.ImageRGBA":
    "make87_messages.detection.box.Box2D":
    "make87_messages.spatial.translation.Translation2D":
    "make87_messages.primitive.SFixed64":
    "make87_messages.transport.http.HTTPRequest":
    "make87_messages.primitive.Bool":
    "make87_messages.geometry.box.Boxes2D":
    "make87_messages.geometry.box.Box2D":
    "make87_messages.image.uncompressed.ImageRGBAny":
    "make87_messages.transport.endpoint.Endpoint":
    "make87_messages.detection.box.Boxes2D":
    "make87_messages.primitive.SInt32":
    "make87_messages.core.Empty":
    "make87_messages.primitive.Bytes":
    "make87_messages.video.FrameAV1":
    "make87_messages.image.uncompressed.ImageYUV422":
    "make87_messages.transport.rtsp.RTSPRequest":
    "make87_messages.primitive.Int32":
    "make87_messages.audio.FrameOpus":
    "make87_messages.image.uncompressed.ImageYUV420":
    "make87_messages.detection.box.Boxes2DAxisAligned":
    "make87_messages.spatial.pose.Pose3D":
    "make87_messages.image.uncompressed.ImageYUV444":
    "make87_messages.audio.FramePcmS16le":
    "make87_messages.image.uncompressed.ImageRGB":
    "make87_messages.primitive.UInt64":
    "make87_messages.image.compressed.ImagePNG":
    "make87_messages.image.uncompressed.ImageRGB888":
    "make87_messages.primitive.Fixed64":
    "make87_messages.primitive.Int64":
    "make87_messages.spatial.translation.Translation1D":
    "make87_messages.text.PlainText":
    "make87_messages.text.LogMessage":
    "make87_messages.tensor.Matrix22":
    "make87_messages.primitive.UInt32":
    "make87_messages.detection.ontology.ModelOntology":
    "make87_messages.video.FrameH264":
    "make87_messages.video.FrameMpegTsAny":
    "make87_messages.spatial.rotation.Quaternion":
    "make87_messages.tensor.Vector4":
    "make87_messages.video.FrameH265":
    "make87_messages.image.uncompressed.ImageRGBA8888":
    "make87_messages.primitive.Double":
    "make87_messages.tensor.Matrix33":
    "make87_messages.transport.auth.DigestAuth":
    "make87_messages.video.FrameAny":
    "make87_messages.video.FrameMpegTsH265":
    "make87_messages.primitive.Float":
    "make87_messages.geometry.box.Box2DAxisAligned":
    "make87_messages.tensor.Vector3":
    "make87_messages.spatial.translation.Translation3D":
    "make87_messages.datetime.Range":
    "make87_messages.core.Header":
    "make87_messages.spatial.pose.Pose2D":
    "make87_messages.tensor.Matrix44":
    "make87_messages.image.compressed.ImageJPEGWithString":
    "make87_messages.file.RelativePathFile":
    "make87_messages.audio.FrameAny":
    "make87_messages.file.AbsolutePathFile":
    "make87_messages.tensor.Vector2":
    "make87_messages.transport.auth.BasicAuth":
    "make87_messages.image.compressed.ImageJPEG":
    "make87_messages.primitive.Fixed32":
    "make87_messages.primitive.SFixed32":
    "make87_messages.datetime.TimeStamp":
    "make87_messages.geometry.box.Boxes2DAxisAligned":
    "make87_messages.transport.auth.BearerToken":
    "make87_messages.primitive.String":
